name: automerge-and-stage

# When a pull request to the develop branch is added, this workflow does the following:
# 1. Automerge feature branch into develop branch
# 2. Build book on develop branch
# 3. Push built pages to staging repo, where it will be deployed

on:
  pull_request:
    branches: develop

env:
  MY_REPO: https://aisingapore:${{secrets.GITHUB_TOKEN}}@github.com/aisingapore/ai-practitioner-handbook.git
  DEVELOP_BRANCH: develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    # 1. Automerge feature branch into develop branch
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Source branch name
      run: echo Running on source branch ${{ github.head_ref }}

    - name: Merge to develop
      run: |
        git clone ${{env.MY_REPO}} -b ${{ github.head_ref }} ~/automerge
        cd ~/automerge
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git fetch origin ${{env.DEVELOP_BRANCH}}
        git merge origin/${{env.DEVELOP_BRANCH}} -Xours
        git checkout ${{env.DEVELOP_BRANCH}}
        git merge ${{ github.head_ref }} -Xtheirs
        git push


    # 2. Builds book on develop branch
    - name: Set up Python 3.8.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.13

    - name: Install dependencies
      run: pip install -r requirements.txt


    # 3. Push built pages to staging repo, where it will be deployed
    - name: Build the book
      run: jupyter-book build ~/automerge

    - name: Make staging dir
      run: |
        mkdir ./staging && \
          cp -r ~/automerge/_build ./staging && \
          cp -r ~/automerge/.github ./staging

    - name: Push to staging repo
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: ./staging
        destination-github-username: 'aisingapore'
        destination-repository-name: 'handbook-staging'
        user-email: bot@example.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: staging