name: automerge-to-develop

on:
  pull_request:
    branches: main

env:
  MY_REPO: https://aisingapore:${{secrets.GITHUB_TOKEN}}@github.com/aisingapore/ai-practitioner-handbook.git
  DEVELOP_BRANCH: develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Source branch name
      run: echo Running on source branch ${{ github.head_ref }}

    - name: Merge with develop
      run: |
        git clone ${{env.MY_REPO}} -b ${GITHUB_REF##*/} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git fetch origin ${{env.DEVELOP_BRANCH}}
        git checkout ${{env.DEVELOP_BRANCH}}
        git merge ${{env.MY_BRANCH}}
        git push