name: proselint

on:
  push:
    paths:
    - book/**

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.13

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v24
      with:
        files: |
          book/**/*.md
        files_ignore: |
          book/assets/*

    # Run English language linter
    - name: Run proselint
      continue-on-error: true
      run: |
        for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
          proselint $file
        done